### ISSUE TITLE
Response 400 from oauth2

### ISSUE THREAD

**Issue by 1pilo** [miaucl/cookidoo-api#26]
I've cloned the repo and tried to run the example script. 
I am getting the following error message:

PS C:\WS\cookidoo-api> python.exe .\example.py
2024-12-03 15:26:28,032 [   DEBUG] asyncio:631 Using proactor: IocpProactor
2024-12-03 15:26:28,820 [   DEBUG] cookidoo_api.cookidoo:233 Response from https://eu.login.vorwerk.com/oauth2/token [400]: {"error":"invalid_grant","error_description":"Bad credentials"}
2024-12-03 15:26:28,821 [   DEBUG] cookidoo_api.cookidoo:260 Exception: Cannot request access token: {"error":"invalid_grant","error_description":"Bad credentials"}
Traceback (most recent call last):
  File "C:\WS\cookidoo-api\example.py", line 141, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\pichler\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\pichler\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\pichler\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\WS\cookidoo-api\example.py", line 50, in main
    await cookidoo.login()
  File "C:\WS\cookidoo-api\cookidoo_api\cookidoo.py", line 201, in login
    return await self._request_access_token(user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WS\cookidoo-api\cookidoo_api\cookidoo.py", line 263, in _request_access_token
    raise CookidooAuthException(
        "Access token request failed due to bad request, please check your email or refresh token."
    )
cookidoo_api.exceptions.CookidooAuthException: Access token request failed due to bad request, please check your email or refresh token.

Is there anything I need to do to make it work?
Email and Password should be correct.

**Comment by miaucl** [comment]
@1pilo Sorry it does not work for you right away. I cannot say if it because of your password, but you can test it using postman. The complete recorded request can be found here: https://github.com/miaucl/cookidoo-api/blob/master/docs/raw-api-requests/login.txt

**Comment by 1pilo** [comment]
hello @miaucl I tried to change the location to "it"  and language to "it". as it is my current location. however it did not work.
Password and Email are set in my current environment as it is suggested and the code from example is 1:1 the same as on the repo.
I will try postman to debug. Just did not use postman until now. Maybe I will see something

**Comment by 1pilo** [comment]
This is my postman result:
![image](https://github.com/user-attachments/assets/e67cda55-be33-43e4-83f9-3c2058f9154a)

with Body:
![image](https://github.com/user-attachments/assets/407adef8-7fcf-4cbe-8781-da121828d242)

**Comment by miaucl** [comment]
> hello @miaucl I tried to change the location to "it" and language to "it". as it is my current location. however it did not work. Password and Email are set in my current environment as it is suggested and the code from example is 1:1 the same as on the repo. I will try postman to debug. Just did not use postman until now. Maybe I will see something

Make sure you use a combination of the `locations.json` file.

        "country_code": "it",
        "language": "it-IT",
        "url": "https://cookidoo.it/foundation/it-IT"


But in your case you are already blocked at the login which is not used be the login. I don't really know what it might be at this point, but you might wanna try to check in your browser, which url is used for the token. I could only test my case, in which `{site}` is `eu`: `https://{site}.login.vorwerk.com/oauth2/token`

If you see something different there, you might have to change it.


<img width="1512" alt="Bildschirmfoto 2024-12-04 um 09 42 19" src="https://github.com/user-attachments/assets/145c45e8-9e98-4965-88f5-73f4bb47f09c">

**Comment by miaucl** [comment]
I switched mine to IT and could login with my credentials without problems.

You sure you have your .env correctly?

```
EMAIL=your_email@gmail.com
PASSWORD=zEnmuh-debhit-123456
```

**Comment by miaucl** [comment]
Else you might also have a look at the smoke test action which verifies the API regularly: https://github.com/miaucl/cookidoo-api/actions/workflows/smoke-test.yaml

**Comment by miaucl** [comment]
Hey @1pilo , some updates.

See https://github.com/home-assistant/core/issues/134583

**Comment by zorch33** [comment]
was having the same issues with .ie (Ireland) for country and only language option was English-UK, Changed country to UK and everything worked ok - this was before the update

**Comment by miaucl** [comment]
@zorch33 See version 0.12.2 to get Ireland working, it was an exception to the rule :)

**Comment by 1pilo** [comment]
@miaucl yes, thanks a lot. Checked it and it worked!
